Add links from Tutorial sections to relevant Samples code.
elmish/Elmish.WPF pull request #486
Opened 2022-06-20 18:01 UTC by rfreytag

Thought it helpful to link the Tutorial sections directly to the referenced Samples source code.

2022-06-20 18:03 UTC, rfreytag commented
This is my first pull request on GitHub so am making it a 'draft pull request.'  Liking Elmish.WPF a lot; thanks.  Hope I can help the project.

2022-06-20 18:04 UTC, the-not-mad-psychologist commented
> This is my first pull request on GitHub so am making it a 'draft pull request.'

Drafts are for while you're still working on PRs. When you're ready for someone to review the PR and consider merging it, mark it "Ready for Review".

2022-06-23 11:04 UTC, TysonMN requested changes
Thanks!

In addition to using relative links, just one more minor adjustment.

2022-06-23 11:04 UTC, TysonMN commented on TUTORIAL.md
> +*Relevant sample: SingleCounter - ([C# wrapper](https://github.com/elmish/Elmish.WPF/tree/master/src/Samples/SingleCounter) which calls [F# core](https://github.com/elmish/Elmish.WPF/tree/master/src/
Adjust your links so they have this format:

> XAML views and F# core

with the links on the obvious words.

2022-06-23 12:45 UTC, closed without merging

2022-06-23 12:53 UTC, rfreytag commented
Seems my method of rewriting my repos branch history by deleting a remote branch closed this pull request.  I have issued another identical pull request with the changes specified by marner2 and TysonMN.  Thanks, Richard F.