Do not throw NullReferenceException when ValueOption.toNull is called on ValueNone of reference type
elmish/Elmish.WPF pull request #550
Opened 2022-12-20 14:33 UTC by LyndonGingerich

`unbox null` throws a `NullReferenceException`. Was this code path perhaps just not tested?

Thanks to @marner2 for figuring out the solution.

2022-12-20 21:10 UTC, marner2 approved these changes

2022-12-21 04:20 UTC, TysonMN requested changes

2022-12-21 04:20 UTC, TysonMN commented on src/Elmish.WPF/InternalUtils.fs
>        if box Unchecked.defaultof<'a> = null then
How about extracting `Unchecked.defaultof<'a>`?

2022-12-21 14:04 UTC, LyndonGingerich commented on src/Elmish.WPF/InternalUtils.fs
>        if box Unchecked.defaultof<'a> = null then
Done.

2022-12-21 14:45 UTC, merged